version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_NAME: booksdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: supersecretkey
    volumes:
      - .:/app
    command: npm run dev

volumes:
  db_data:
